@echo off
echo Starting backend server...
start "Backend" cmd /k ".venv\Scripts\activate.bat && uvicorn main:app --reload"
echo Starting frontend server...
start "Frontend" cmd /k "cd frontend && npm run dev"
